SUMMARY = "Google API client core library"
HOMEPAGE = "https://github.com/googleapis/google-cloud-python"
SECTION = "devel/python"

LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57"

inherit pypi

SRC_URI[md5sum] = "173191c89a7e799719dfa79f02542d93"
SRC_URI[sha256sum] = "16b14c0492154110d869a08be22d27440010057fd826205303c7edaa1c3cd71e"

BBCLASSEXTEND = "native"
